import pyautogui
from time import sleep

def write(char):
    pyautogui.write(char)
    pyautogui.press('enter')

order = input("order of the things (1 lowest, 2 mid, 3 high): ")
input()
pyautogui.click(1562,1111)

write('4')
sleep(1.5)

foot = 1.5

if order == "123":
    # print("the order is", returnVal[3], returnVal[2], returnVal[1])
    write('r')
    sleep(1.5)
    write('3')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('w')
    sleep(foot)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('w')
    sleep(foot)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('w')
    sleep(foot)
    write('q')
    sleep(1.5)
elif order == "132":
    # print("the order is", returnVal[3], returnVal[1], returnVal[2])
    write('r')
    sleep(1.5)
    write('3')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('w')
    sleep(foot*2)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('s')
    sleep(foot)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('w')
    sleep(foot*2)
    write('q')
    sleep(1.5)
elif order == "213":
    # print("the order is", returnVal[2], returnVal[3], returnVal[1])
    write('r')
    sleep(1.5)
    write('w')
    sleep(foot)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('s')
    sleep(foot+0.3)
    write('q')
    sleep(1.5)
    write('3')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('w')
    sleep(foot*2)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('w')
    sleep(foot)
    write('q')
    sleep(1.5)

elif order == "231":
    # print("the order is", returnVal[2], returnVal[1], returnVal[3])
    write('r')
    sleep(1.5)
    write('w')
    sleep(foot)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('w')
    sleep(foot)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('s')
    sleep((foot*2)+0.3)
    write('q')
    sleep(1.5)
    write('3')
    sleep(1.5)
    write('4')
    sleep(1.5)


elif order == "312":
    # print("the order is", returnVal[1], returnVal[3], returnVal[2])
    write('r')
    sleep(1.5)
    write('w')
    sleep(foot*2)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('s')
    sleep((foot*2)+0.3)
    write('q')
    sleep(1.5)
    write('3')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('w')
    sleep(foot)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)

    


elif order == "321":
    # print("the order is", returnVal[1], returnVal[2], returnVal[3])
    write('r')
    sleep(1.5)
    write('w')
    sleep(foot*2)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('s')
    sleep(foot)
    write('q')
    sleep(1.5)
    write('0')
    sleep(5)
    write('2')
    sleep(1.5)
    write('5')
    sleep(1.5)
    write('4')
    sleep(1.5)
    write('s')
    sleep(foot+0.3)
    write('q')
    sleep(1.5)
    write('3')
    sleep(1.5)
    write('4')
    sleep(1.5)